name: bilibili log
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: main
jobs:
   bilibili-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Curl ðŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          date +%Y_%m_%d%t%H:%M:%S >> bilibili.log
          curl -o /dev/null -s -w "å»ºç«‹åˆ°æœåŠ¡å™¨çš„ TCP è¿žæŽ¥æ‰€ç”¨çš„æ—¶é—´ï¼š%{time_connect}\næœåŠ¡å™¨è¿”å›žæ•°æ®çš„ç¬¬ä¸€ä¸ªå­—èŠ‚æ‰€ç”¨çš„æ—¶é—´ï¼š%{time_starttransfer}\nå®Œæˆè¯·æ±‚æ‰€ç”¨çš„æ—¶é—´ï¼š%{time_total}\nçŠ¶æ€ç ï¼š%{http_code}\n\n" http://www.bilibili.com >> bilibili.log
        env:
          CI: false

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main # The branch the action should deploy to.
          FOLDER: . # The folder the action should deploy.
